version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: foodblog_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: food_blog_db
      MYSQL_USER: food_blog_user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./Server
    image: foodblog_backend
    container_name: foodblog_backend
    working_dir: /Server
    volumes:
      - ./Server:/Server
    ports:
      - "5000:5000"
    command: ["npm", "start"]
    depends_on:
      - database

  frontend:
    build:
      context: ./Client
    image: foodblog_frontend
    container_name: foodblog_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
